// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StateNationalParkApi.Models;

#nullable disable

namespace StateNationalParkApi.Migrations
{
    [DbContext(typeof(StateNationalParkApiContext))]
    [Migration("20230211025444_TestData")]
    partial class TestData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("StateNationalParkApi.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ParkName")
                        .HasColumnType("longtext");

                    b.Property<string>("ParkState")
                        .HasColumnType("longtext");

                    b.Property<string>("StateOrNational")
                        .HasColumnType("longtext");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            ParkName = "Crater Lake",
                            ParkState = "Oregon",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 2,
                            ParkName = "Yosemite",
                            ParkState = "California",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 3,
                            ParkName = "Champoeg",
                            ParkState = "Oregon",
                            StateOrNational = "State"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
